name = "SymbolicCompilerPasses"
uuid = "3384d301-0fbe-4b40-9ae0-b0e68bedb069"
version = "0.1.2"
authors = ["Dhairya Gandhi <dhairya@juliahub.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[weakdeps]
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"

[sources.SymbolicUtils]
rev = "dg/opt_api"
url = "https://github.com/DhairyaLGandhi/SymbolicUtils.jl"

[extensions]
SCPLinearSolveExt = ["LinearSolve"]

[compat]
LinearAlgebra = "1"
LinearSolve = "3.53.0"
PreallocationTools = "0.4.34, 1"
StaticArrays = "1.9.15, 1"
SymbolicUtils = "4.1.0"
julia = "1.10"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "SafeTestsets", "Test"]
